set nocompatible "关闭 vi 兼容模式
syntax on "自动语法高亮
colorscheme molokai "dracula 设定配色方案 molokai
filetype on "开启文件类型检测
filetype indent on "不同文件采用不同缩进
filetype plugin on "开启插件
filetype plugin indent on "自动补全
set completeopt=longest,menu

"自动补全命令时候使用菜单式匹配列表
set wildmenu
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType java set omnifunc=javacomplete#Complet

set list
set listchars=tab:→\ ,space:·,nbsp:␣,trail:•,eol:¶,precedes:«,extends:»
"set listchars=tab:>-
"set listchars=trail:-

set nowrap "取消换行
"set number "显示行号
set relativenumber "显示相对行号
set cursorline "突出显示当前行
set ruler "打开状态栏标尺
set shiftwidth=4 "设定 << 和 >> 命令移动时的宽度为 4
set softtabstop=4 "使得按退格键时可以一次删掉 4 个空格
set tabstop=4 "设定 tab 长度为 4
set nobackup "覆盖文件时不备份
set autochdir "自动切换当前目录为当前文件所在的目录
set backupcopy=yes "设置备份时的行为为覆盖
set ignorecase smartcase "搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set nowrapscan "禁止在搜索到文件两端时重新搜索
set incsearch "输入搜索内容时就显示搜索结果
set hlsearch "搜索时高亮显示被找到的文本
set noerrorbells "关闭错误信息响铃
set novisualbell "关闭使用可视响铃代替呼叫
set t_vb= "置空错误铃声的终端代码
set magic "设置魔术
set hidden "允许在有未保存的修改时切换缓冲区，此时的修改由 vim 负责保存
set guioptions-=T "隐藏工具栏
set guioptions-=m "隐藏菜单栏
set smartindent "开启新行时使用智能自动缩进
set backspace=indent,eol,start
"不设定在插入状态无法用退格键和 Delete 键删除回车符
set cmdheight=1 "设定命令行的行数为 1
set laststatus=2 "显示状态栏 (默认值为 1, 无法显示状态栏)

"关闭vi模式
set nocp

"与windows共享剪贴板
set clipboard+=unnamed

"历史命令保存行数
set history=100

"当文件被外部改变时自动读取
set autoread

"允许使用鼠标点击定位
set mouse=a

"允许区域选择
set selection=exclusive
set selectmode=mouse,key

"状态栏显示当前执行的命令
set showcmd

"粘贴时保持格式
set paste

"继承前一行的缩进方式，特别适用于多行注释
set autoindent

"允许使用退格键，或set backspace=2
set whichwrap+=<,>,h,l

"光标移动到buffer的顶部和底部时保持3行距离, 或set so=3
set scrolloff=3

"设定默认解码
"set fenc=utf-8
"set fencs=utf-8,usc-bom,euc-jp,gb18030,gbk,gb2312,cp936

"set showmatch "插入括号时，短暂地跳转到匹配的对应括号
"set matchtime=2 "短暂跳转到匹配括号的时间

"取消自动备份及产生swp文件
"set nowb
"set noswapfile

"使用C样式的缩进
"set cindent

"在被分割的窗口间显示空白，便于阅读
"set fillchars=vert:\ ,stl:\ ,stlnc:\

"http://blog.csdn.net/g_brightboy/article/details/14229139
